client_id = "f42b0c69c93f467aa2391169f1427520"
name = "Confirmo V2"
application_url = "https://confirmo-sbc8.onrender.com/app"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-10"

[[webhooks.subscriptions]]
topics = ["orders/create"]
uri = "https://confirmo-sbc8.onrender.com/webhooks/orders/create"

[access_scopes]
scopes = "read_orders,write_orders,read_customers"

[auth]
redirect_urls = [
  "https://confirmo-sbc8.onrender.com/auth/callback"
]
